# Generated by Django 6.0.7 on 2026-08-03 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category Name e.g. Restaurants & Cafes', max_length=100)),
                ('slug', models.SlugField(help_text='Unique slug e.g. restaurant', max_length=100, unique=True)),
                ('icon_name', models.CharField(default='Briefcase', help_text='Icon identifier e.g. Utensils, Dumbbell, Laptop', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Short description of the category')),
            ],
            options={
                'verbose_name': 'Business Category',
                'verbose_name_plural': 'Business Categories',
            },
        ),
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template Title e.g. Bistro Gourmet', max_length=100)),
                ('slug', models.SlugField(help_text='Unique template identifier slug e.g. bistro-gourmet', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of template features')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image preview URL', max_length=500)),
                ('default_tagline', models.CharField(default='Welcome to our business', help_text='Default tagline if user leaves blank', max_length=255)),
                ('default_primary_color', models.CharField(default='#2563eb', help_text='Default accent hex color e.g. #2563eb', max_length=20)),
                ('default_hero_image_url', models.URLField(blank=True, help_text='Default high-res hero image URL', max_length=500)),
                ('default_services', models.JSONField(blank=True, default=list, help_text="List of service objects: [{'title': '...', 'desc': '...', 'img': '...', 'tag': '...'}]")),
                ('default_testimonials', models.JSONField(blank=True, default=list, help_text="List of testimonial objects: [{'quote': '...', 'author': '...', 'role': '...', 'avatar': '...'}]")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is visible and selectable for generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='config.businesscategory')),
            ],
            options={
                'verbose_name': 'Website Template',
                'verbose_name_plural': 'Website Templates',
            },
        ),
        migrations.CreateModel(
            name='GeneratedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.CharField(max_length=64, unique=True)),
                ('business_name', models.CharField(max_length=150)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('content_data', models.JSONField(default=dict, help_text='Full rendered website JSON payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.businesscategory')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.websitetemplate')),
            ],
            options={
                'verbose_name': 'Generated Website',
                'verbose_name_plural': 'Generated Websites',
            },
        ),
    ]
