# Generated by Django 6.0.7 on 2026-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(help_text='Full GitHub URL e.g. https://github.com/user/repo', max_length=500, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stars_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, default='TypeScript', max_length=50)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('default_branch', models.CharField(default='main', max_length=50)),
                ('readme_markdown', models.TextField(blank=True)),
                ('file_tree', models.JSONField(blank=True, default=list)),
                ('detected_variables', models.JSONField(blank=True, default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub Template',
                'verbose_name_plural': 'GitHub Templates',
            },
        ),
    ]
