# Generated by Django 6.0.7 on 2026-08-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_githubtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubtemplate',
            name='detected_variables',
        ),
        migrations.RemoveField(
            model_name='githubtemplate',
            name='file_tree',
        ),
        migrations.RemoveField(
            model_name='githubtemplate',
            name='language',
        ),
        migrations.RemoveField(
            model_name='githubtemplate',
            name='readme_markdown',
        ),
        migrations.RemoveField(
            model_name='githubtemplate',
            name='topics',
        ),
        migrations.AddField(
            model_name='githubtemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for sorting & filtering templates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_templates', to='config.businesscategory'),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='default_branch',
            field=models.CharField(default='main', help_text='Default Git branch (e.g. main, master)', max_length=50),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of what this template provides'),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='forks_count',
            field=models.IntegerField(default=0, help_text='Number of GitHub Forks'),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='is_popular',
            field=models.BooleanField(default=True, help_text='Show in Featured/Popular section'),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='owner',
            field=models.CharField(blank=True, help_text='GitHub Owner/Username (auto-filled if blank)', max_length=100),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='repo_name',
            field=models.CharField(blank=True, help_text='Repository Name (auto-filled if blank)', max_length=100),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='repo_url',
            field=models.URLField(help_text='Full GitHub Repository URL e.g. https://github.com/user/repo', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='stars_count',
            field=models.IntegerField(default=0, help_text='Number of GitHub Stars'),
        ),
        migrations.AlterField(
            model_name='githubtemplate',
            name='title',
            field=models.CharField(help_text='Template Display Title e.g. SaaS Subscription Platform', max_length=200),
        ),
    ]
