# Generated by Django 6.0.7 on 2026-08-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_githubtemplate_detected_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtemplate',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Visual preview thumbnail image URL of the website', max_length=500),
        ),
    ]
