# Generated by Django 6.0.7 on 2026-08-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_githubtemplate_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedwebsite',
            name='template',
        ),
        migrations.AddField(
            model_name='generatedwebsite',
            name='github_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.githubtemplate'),
        ),
        migrations.DeleteModel(
            name='WebsiteTemplate',
        ),
    ]
