# Generated by Django 6.0.7 on 2026-08-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remove_generatedwebsite_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedwebsite',
            name='source_code_css',
            field=models.TextField(blank=True, default='', help_text='Stored CSS source code'),
        ),
        migrations.AddField(
            model_name='generatedwebsite',
            name='source_code_html',
            field=models.TextField(blank=True, default='', help_text='Stored HTML source code'),
        ),
        migrations.AddField(
            model_name='generatedwebsite',
            name='source_code_js',
            field=models.TextField(blank=True, default='', help_text='Stored JS source code'),
        ),
        migrations.AddField(
            model_name='githubtemplate',
            name='editable_placeholders',
            field=models.JSONField(blank=True, default=dict, help_text='Schema of editable placeholder fields detected in source code'),
        ),
        migrations.AddField(
            model_name='githubtemplate',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='True if repository code has been imported & stored'),
        ),
        migrations.AddField(
            model_name='githubtemplate',
            name='source_code_css',
            field=models.TextField(blank=True, default='', help_text='Stored imported CSS stylesheet source code from GitHub'),
        ),
        migrations.AddField(
            model_name='githubtemplate',
            name='source_code_html',
            field=models.TextField(blank=True, default='', help_text='Stored imported HTML source code from GitHub'),
        ),
        migrations.AddField(
            model_name='githubtemplate',
            name='source_code_js',
            field=models.TextField(blank=True, default='', help_text='Stored imported JS interactivity scripts from GitHub'),
        ),
    ]
