# Generated by Django 6.0.7 on 2026-08-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_generatedwebsite_source_code_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtemplate',
            name='logo_type',
            field=models.CharField(choices=[('text', 'Text Logo Only'), ('image', 'Image Logo Only'), ('both', 'Supports Text & Image Logo')], default='both', help_text='Detected logo type from template analysis: text, image, or both', max_length=20),
        ),
    ]
