from django.db import models

class BusinessCategory(models.Model):
    """
    Represents an industry niche category (e.g. Restaurants & Cafes, Fitness & Gyms).
    Admins can add new categories directly from the Django Admin Panel.
    """
    name = models.CharField(max_length=100, help_text="Category Name e.g. Restaurants & Cafes")
    slug = models.SlugField(max_length=100, unique=True, help_text="Unique slug e.g. restaurant")
    icon_name = models.CharField(max_length=50, default="Briefcase", help_text="Icon identifier e.g. Utensils, Dumbbell, Laptop")
    description = models.TextField(blank=True, help_text="Short description of the category")
    price = models.IntegerField(default=499, help_text="Price in INR for templates under this category")

    class Meta:
        verbose_name = "Business Category"
        verbose_name_plural = "Business Categories"

    def __str__(self):
        return self.name


class GeneratedWebsite(models.Model):
    """
    Stores websites generated by users with replaced placeholders.
    """
    website_id = models.CharField(max_length=64, unique=True)
    business_name = models.CharField(max_length=150)
    category = models.ForeignKey(BusinessCategory, on_delete=models.SET_NULL, null=True)
    github_template = models.ForeignKey('GitHubTemplate', on_delete=models.SET_NULL, null=True, blank=True)
    
    logo_url = models.URLField(max_length=500, blank=True)
    hero_image_url = models.URLField(max_length=500, blank=True)
    tagline = models.CharField(max_length=255, blank=True)
    primary_color = models.CharField(max_length=20, blank=True)
    contact_email = models.EmailField(blank=True)
    contact_phone = models.CharField(max_length=50, blank=True)

    content_data = models.JSONField(default=dict, help_text="Full rendered website JSON payload")
    source_code_html = models.TextField(blank=True, default='', help_text="Stored HTML source code")
    source_code_css = models.TextField(blank=True, default='', help_text="Stored CSS source code")
    source_code_js = models.TextField(blank=True, default='', help_text="Stored JS source code")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Generated Website"
        verbose_name_plural = "Generated Websites"

    def __str__(self):
        return f"{self.business_name} ({self.website_id})"


class GitHubTemplate(models.Model):
    """
    Stores GitHub repository templates categorized by Business Niche.
    """
    category = models.ForeignKey(
        BusinessCategory,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='github_templates',
        help_text="Category for sorting & filtering templates"
    )
    title = models.CharField(max_length=200, help_text="Template Display Title e.g. SaaS Subscription Platform")
    repo_url = models.URLField(max_length=500, unique=True, help_text="Full GitHub Repository URL e.g. https://github.com/user/repo")
    owner = models.CharField(max_length=100, blank=True, help_text="GitHub Owner/Username (auto-filled if blank)")
    repo_name = models.CharField(max_length=100, blank=True, help_text="Repository Name (auto-filled if blank)")
    description = models.TextField(blank=True, help_text="Short description of what this template provides")
    thumbnail_url = models.URLField(max_length=500, blank=True, help_text="Visual preview thumbnail image URL of the website")
    stars_count = models.IntegerField(default=0, help_text="Number of GitHub Stars")
    forks_count = models.IntegerField(default=0, help_text="Number of GitHub Forks")
    default_branch = models.CharField(max_length=50, default="main", help_text="Default Git branch (e.g. main, master)")
    is_popular = models.BooleanField(default=True, help_text="Show in Featured/Popular section")

    LOGO_TYPE_CHOICES = [
        ('text', 'Text Logo Only'),
        ('image', 'Image Logo Only'),
        ('both', 'Supports Text & Image Logo'),
    ]
    logo_type = models.CharField(
        max_length=20,
        choices=LOGO_TYPE_CHOICES,
        default='both',
        help_text="Detected logo type from template analysis: text, image, or both"
    )

    source_code_html = models.TextField(blank=True, default='', help_text="Stored imported HTML source code from GitHub")
    source_code_css = models.TextField(blank=True, default='', help_text="Stored imported CSS stylesheet source code from GitHub")
    source_code_js = models.TextField(blank=True, default='', help_text="Stored imported JS interactivity scripts from GitHub")
    is_imported = models.BooleanField(default=False, help_text="True if repository code has been imported & stored")
    editable_placeholders = models.JSONField(default=dict, blank=True, help_text="Schema of editable placeholder fields detected in source code")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "GitHub Template"
        verbose_name_plural = "GitHub Templates"

    def save(self, *args, **kwargs):
        # 1. Auto extract owner and repo_name from repo_url if not provided or clean them up
        try:
            if self.repo_url:
                from .github_importer import parse_github_repo_url
                parsed_owner, parsed_repo, parsed_branch = parse_github_repo_url(self.repo_url)
                if parsed_owner and not self.owner:
                    self.owner = parsed_owner
                if parsed_repo and not self.repo_name:
                    self.repo_name = parsed_repo
                if parsed_branch and (not self.default_branch or self.default_branch == 'main'):
                    self.default_branch = parsed_branch
        except Exception:
            pass

        # 2. Auto import source code from GitHub if not already provided or if source_code_html is missing
        if not self.source_code_html or not self.is_imported:
            try:
                from .github_importer import import_source_from_github, get_default_category_template
                cat_slug = self.category.slug if self.category else ''
                imported_res = import_source_from_github(
                    owner=self.owner or 'template-owner',
                    repo_name=self.repo_name or 'template-repo',
                    branch=self.default_branch or 'main',
                    category_slug=cat_slug,
                    title=self.title or self.repo_name or 'Modern Template'
                )
                if imported_res and imported_res.get('html'):
                    self.source_code_html = imported_res.get('html', '')
                    self.source_code_css = imported_res.get('css', '')
                    self.source_code_js = imported_res.get('js', '')
                    self.editable_placeholders = imported_res.get('placeholders', {})
                    self.is_imported = True
                else:
                    # Fallback to category template if import returned empty
                    def_html, def_css, def_js, def_ph = get_default_category_template(
                        category_slug=cat_slug,
                        title=self.title or self.repo_name or 'Modern Template',
                        owner=self.owner or 'templates',
                        repo_name=self.repo_name or 'starter'
                    )
                    self.source_code_html = def_html
                    self.source_code_css = def_css
                    self.source_code_js = def_js
                    self.editable_placeholders = def_ph
                    self.is_imported = True
            except Exception as imp_err:
                try:
                    from .github_importer import get_default_category_template
                    cat_slug = self.category.slug if self.category else ''
                    def_html, def_css, def_js, def_ph = get_default_category_template(
                        category_slug=cat_slug,
                        title=self.title or self.repo_name or 'Modern Template',
                        owner=self.owner or 'templates',
                        repo_name=self.repo_name or 'starter'
                    )
                    self.source_code_html = def_html
                    self.source_code_css = def_css
                    self.source_code_js = def_js
                    self.editable_placeholders = def_ph
                    self.is_imported = True
                except Exception:
                    pass

        # 3. Run Template Analysis Engine to classify logo capabilities
        try:
            if self.source_code_html:
                from .template_analyzer import analyze_template_logo_type
                self.logo_type = analyze_template_logo_type(
                    self.source_code_html,
                    self.source_code_css,
                    self.source_code_js
                )
        except Exception:
            if not self.logo_type:
                self.logo_type = 'both'

        super().save(*args, **kwargs)


class PhonePeOrderTransaction(models.Model):
    """
    Stores server-verified PhonePe Payment Gateway transactions and status tracking.
    """
    STATUS_CHOICES = [
        ('PENDING', 'Payment Pending'),
        ('SUCCESS', 'Payment Successful'),
        ('FAILED', 'Payment Failed'),
        ('CANCELLED', 'Payment Cancelled'),
    ]

    merchant_transaction_id = models.CharField(max_length=100, unique=True, db_index=True)
    phonepe_transaction_id = models.CharField(max_length=100, blank=True, null=True)
    provider_reference_id = models.CharField(max_length=100, blank=True, null=True)
    business_name = models.CharField(max_length=150)
    template_name = models.CharField(max_length=150, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=499.00)
    currency = models.CharField(max_length=10, default='INR')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING', db_index=True)
    is_paid = models.BooleanField(default=False)
    upi_id = models.CharField(max_length=100, blank=True)
    customer_phone = models.CharField(max_length=20, blank=True)
    raw_response_payload = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "PhonePe Order Transaction"
        verbose_name_plural = "PhonePe Order Transactions"
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.merchant_transaction_id} - {self.business_name} ({self.status})"




